package com.cursosdedesarrollo.app.selenium;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BusquedaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void busqueda() {
    // Test name: busqueda
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://cursosdedesarrollo.com/");
    // 2 | setWindowSize | 2103x1256 | 
    driver.manage().window().setSize(new Dimension(2103, 1256));
    // 3 | click | id=wp-block-search__input-1 | 
    driver.findElement(By.id("wp-block-search__input-1")).click();
    // 4 | type | id=wp-block-search__input-1 | docker
    driver.findElement(By.id("wp-block-search__input-1")).sendKeys("docker");
    // 5 | click | css=.wp-block-search__button | 
    driver.findElement(By.cssSelector(".wp-block-search__button")).click();
    // 6 | click | css=h1 | 
    driver.findElement(By.cssSelector("h1")).click();
    // 7 | waitForText | css=h1 | Search results for: docker
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.textToBe(By.cssSelector("h1"), "Search results for: docker"));
    }
    // 8 | assertText | css=h1 | Search results for: docker

    assertEquals("Search results for: docker",driver.findElement(By.cssSelector("h1")).getText());
  }
}
